ignore docusaurus and dockerhub, but go after others.
diem/diem pull request #6951
Opened 2020-12-16 23:27 UTC by rexhoffman

## Motivation

Remove more references to libra where possible.

### Have you read the [Contributing Guidelines on pull requests]

Yes

## Test Plan

combo of CI for gha and @JoelMarcey for the website changes.

## Related PRs

None

2020-12-17 18:03 UTC, JoelMarcey commented
@rexhoffman Would also like to land this after the actual site switch. And we can do whatever rebasing/merging after that.

2020-12-18 03:22 UTC, JoelMarcey commented on developers.diem.com/src/README.md
> +[GitHub repo](https://github.com/diem/website).
None of this publishing stuff is true any longer. I think we need a vet of the READMEs and other info files for accuracy. We can leave for now and do a cleanup pass later.

2020-12-18 03:23 UTC, JoelMarcey commented on developers.diem.com/docs/node/overview.md
> +    icon="img/diem-nodes.svg"
We would need to rename the actual images too, right? 

They would be in `developers.diem.com/static/img`

2020-12-18 03:24 UTC, JoelMarcey requested changes
Need to rename a couple of actual image files since you change their name here.

I would also rebase this too and repush.

2020-12-18 16:50 UTC, rexhoffman commented
@JoelMarcey sure this can wait, are we getting this remamed?   

https://github.com/dfuzr/libra-developer-plugins

Referenced heavily in the site.

2020-12-18 16:57 UTC, libra-action commented
**release binaries dependency change summary**:
```
target packages:
  M ureq 1.5.4 (direct third-party, crates.io)
    * version upgraded from 1.5.2
    * (unchanged features: json, native-tls, serde, serde_json)
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M lock_api 0.4.2 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M mio 0.6.23 (transitive third-party, crates.io)
    * version upgraded from 0.6.22
    * (unchanged features: default, with-deprecated)
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M socket2 0.3.18 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
  M tracing 0.1.22 (transitive third-party, crates.io)
    * version upgraded from 0.1.21
    * (unchanged features: log, std)
```
<!-- metadata: {"tag":"release-summary"} -->

2020-12-18 16:57 UTC, libra-action commented
**LSR dependency change summary**:
```
target packages:
  M ureq 1.5.4 (direct third-party, crates.io)
    * version upgraded from 1.5.2
    * (unchanged features: json, native-tls, serde, serde_json)
  M lock_api 0.4.2 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
```
<!-- metadata: {"tag":"lsr-summary"} -->

2020-12-18 16:57 UTC, libra-action commented
**LEC dependency change summary**:
```
target packages:
  M ureq 1.5.4 (direct third-party, crates.io)
    * version upgraded from 1.5.2
    * (unchanged features: json, native-tls, serde, serde_json)
  M libc 0.2.81 (transitive third-party, crates.io)
    * added features: align
    * (unchanged features: default, std)
  M lock_api 0.4.2 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M mio 0.6.23 (transitive third-party, crates.io)
    * version upgraded from 0.6.22
    * (unchanged features: default, with-deprecated)
  M openssl-sys 0.9.59 (transitive third-party, crates.io)
    * version upgraded from 0.9.58
    * (unchanged features: [none])
  M parking_lot 0.11.1 (transitive third-party, crates.io)
    * version upgraded from 0.11.0
    * (unchanged features: default)
  M socket2 0.3.18 (transitive third-party, crates.io)
    * version upgraded from 0.3.15
    * (unchanged features: [none])
  M tracing 0.1.22 (transitive third-party, crates.io)
    * version upgraded from 0.1.21
    * (unchanged features: log, std)
```
<!-- metadata: {"tag":"lec-summary"} -->

2021-01-21 18:05 UTC, closed without merging