[cluster-test] Clone vault image to ECR and pull from ECR instead of …
diem/diem pull request #7328
Opened 2021-01-22 19:28 UTC by snakech

…dockerhub

related pr: novifinancial/libra-ops#901 for create new vault repo on ECR

## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/master/developers.diem.com, and link to your PR here.)

2021-01-22 19:29 UTC, snakech commented
please let me know if I missed any corresponded places need to change. Also may I ask if there has any test plan? Do I need to merge pr to create new repo first and then do CT test with this PR?

2021-01-22 21:46 UTC, sausagee requested changes

2021-01-22 21:46 UTC, sausagee commented on docker/dockerhub_to_novi_ecr.sh
> +docker pull --disable-content-trust=false docker.io/libra/vault:"1.4.0"
This should be just `vault`.

2021-01-22 21:46 UTC, sausagee commented on docker/dockerhub_to_novi_ecr.sh
> +docker push --disable-content-trust=true "$TARGET_REPO"/diem/vault:"1.4.0"
same here and the two references below.

2021-01-22 23:08 UTC, sausagee approved these changes

2021-01-23 04:44 UTC, rexhoffman commented on docker/dockerhub_to_novi_ecr.sh
> +docker pull --disable-content-trust=false docker.io/vault:"1.4.0"
Given this file has no hard coded version numbers I'm loath to have it take them on now.   At the very least this should be input for the file, at best there should be a single file that acts as the source of truth for the vault version, and given the sensitivity of the software perhaps a sha version pull as well, like in all our debian base versions in our docker builds.    But by having that single file perhaps RUNTIME_SERVICES, set up with things like vault=1.4.0@sha256:<sha> we could use it as input here to make sure we pull the exact file we want, and elsewhere use that version number as a way to reference it.

2021-01-23 04:47 UTC, rexhoffman commented
I wont block this, not knowing the severity of the issue, or your workload.   But.   This is adding cut&paste version numbers to a release file that never had them before.   This adds debt that will eventually cause broken releases, confusion and pain unless someone else pays down that debt for you.    I left a comment on how I think you can minimize that debt if you must add it, but I must admit I was very much hoping you'd figure out the k8s pull so that CI would have to move these files which it is not signing, or tagging.    This is pure debt being added due to existing debt in k8s.

2021-01-25 17:45 UTC, snakech commented
> I wont block this, not knowing the severity of the issue, or your workload. But. This is adding cut&paste version numbers to a release file that never had them before. This adds debt that will eventually cause broken releases, confusion and pain unless someone else pays down that debt for you. I left a comment on how I think you can minimize that debt if you must add it, but I must admit I was very much hoping you'd figure out the k8s pull so that CI would not have to move these files which it is not signing, or tagging. This is pure debt being added due to existing debt in k8s.

Thx for reviewing and suggestion, this is a prety temp solution for now to unblock the LBT and make pr landing works again. Login to k8s and remove all hard code version is the next step I will do

2021-01-26 03:10 UTC, snakech commented
Since we do rarely update vault image, I manually tag an image vault-1.4.0 and push to ecr instead of clone image every time for each LBT run

2021-01-26 03:13 UTC, snakech commented
tested with 
```
./scripts/cti -T dev_czh_pull_7328 --suite land_blocking
2021-01-25T23:58:50.092234Z [main] INFO testsuite/cluster-test/src/aws.rs:28 Scaling to desired_capacity : 0, buffer: 0, asg_name: ct-0-k8s-testnet-validators
all up : 924 TPS, 4898 ms latency, 6450 ms p99 latency, no expired txns
```

2021-01-26 03:16 UTC, snakech commented
/land

2021-01-26 04:08 UTC, merged