Feat bitvec test
diem/diem pull request #7432
Opened 2021-02-01 08:34 UTC by zgfzgf

optimize bitvec test

2021-02-02 01:27 UTC, phlip9 requested changes
Thanks for the contribution! Just a few minor fixes needed and then we can land this : )

2021-02-02 01:27 UTC, phlip9 commented on common/bitvec/src/lib.rs
> -/// ```ignore
Deleting this line will disable to doctest, so let's keep it and change the `ignore` to `rust` so our example doesn't drift : )

2021-02-02 01:27 UTC, phlip9 commented on common/bitvec/src/lib.rs
> +/// assert_eq!(bv.last_set_bit(), 5);
It look like `last_set_bit` returns an `Option<_>`, so you want

```suggestion
/// assert_eq!(bv.last_set_bit(), Some(5));
```

2021-02-02 01:27 UTC, phlip9 commented on common/bitvec/src/lib.rs
> +        let p6 = BitVec { inner: vec![128u8] };
let's write this as a binary literal so the test is clearer

```suggestion
        let p6 = BitVec { inner: vec![0b1000_0000] };
```

2021-02-02 01:27 UTC, phlip9 commented on common/bitvec/src/lib.rs
> +        for i in 0..=std::u8::MAX {
good catch!

2021-02-02 01:27 UTC, phlip9 commented on common/bitvec/src/lib.rs
> -/// ```ignore
I think we also need a `use diem_bitvec::BitVec;` at the start of this doctest

2021-02-02 01:27 UTC, bors-libra commented
:exclamation: Invalid command

<details>
<summary>Bors help and documentation</summary>
<br />

Bors is a Github App used to manage merging of PRs in order to ensure that CI is always green. It does so by maintaining a [Merge Queue](https://github.com/diem/diem/projects/2). Once a PR reaches the head of the Merge Queue it is rebased on top of the latest version of the PR's `base-branch` (generally `master`) and then triggers CI. If CI comes back green the PR is then merged into the `base-branch`. Regardless of the outcome, the next PR is the queue is then processed.

### General
- This project's Merge Queue can be found [here](https://github.com/diem/diem/projects/2).
- This project requires PRs to be [Reviewed](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews) and Approved before they can be queued for merging.
- Before PR's can be merged they must be configured with ["Allow edits from maintainers"](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) enabled. This is needed for Bors to be able to update PR's in-place so that Github can properly recognize and mark them as "merged" once they've been merged into the upstream branch.
### Commands
Bors actions can be triggered by posting a comment which includes a line of the form `/<action>`.
| Command | Action | Description |
| --- | --- | --- |
| __Land__ | `land`, `merge` | attempt to land or merge a PR |
| __Canary__ | `canary`, `try` | canary a PR by performing all checks without merging |
| __Cancel__ | `cancel`, `stop` | stop an in-progress land |
| __Cherry Pick__ | `cherry-pick <target>` | cherry-pick a PR into `<target>` branch |
| __Priority__ | `priority` | set the priority level for a PR (`high`, `normal`, `low`) |
| __Help__ | `help`, `h` | show this help message |

### Options
Options for Pull Requests are configured through the application of labels.
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Option&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | Description |
| --- | --- |
| ![label: bors-high-priority](https://img.shields.io/static/v1?label=&message=bors-high-priority&color=lightgrey) | Indicates that the PR is high-priority. When queued the PR will be placed at the head of the merge queue. |
| ![label: bors-low-priority](https://img.shields.io/static/v1?label=&message=bors-low-priority&color=lightgrey) | Indicates that the PR is low-priority. When queued the PR will be placed at the back of the merge queue. |
| ![label: bors-squash](https://img.shields.io/static/v1?label=&message=bors-squash&color=lightgrey) | Before merging the PR will be squashed down to a single commit, only retaining the commit message of the first commit in the PR. |

</details>

2021-02-02 03:30 UTC, libra-action commented
**LSR dependency change summary**:
```
target packages:
  M sha2 0.9.3 (direct third-party, crates.io)
    * version upgraded from 0.9.2
    * (unchanged features: default, std)
  M libc 0.2.84 (transitive third-party, crates.io)
    * version upgraded from 0.2.82
    * (unchanged features: default, std)
```
<!-- metadata: {"tag":"lsr-summary"} -->

2021-02-02 03:30 UTC, libra-action commented
**LEC dependency change summary**:
```
target packages:
  M sha2 0.9.3 (direct third-party, crates.io)
    * version upgraded from 0.9.2
    * (unchanged features: default, std)
  M smallvec 1.6.1 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: [none])
  M libc 0.2.84 (transitive third-party, crates.io)
    * version upgraded from 0.2.82
    * (unchanged features: align, default, std)
  M tokio-util 0.6.3 (transitive third-party, crates.io)
    * version upgraded from 0.6.2
    * (unchanged features: codec, default)
  R async-stream 0.3.0 (transitive third-party, crates.io)
    * (old features: [none])
  R tokio-stream 0.1.2 (transitive third-party, crates.io)
    * (old features: default, time)

host packages:
  R async-stream-impl 0.3.0 (transitive third-party, crates.io)
    * (old features: [none])
```
<!-- metadata: {"tag":"lec-summary"} -->

2021-02-02 03:30 UTC, libra-action commented
**release binaries dependency change summary**:
```
target packages:
  A rental 0.5.5 (direct third-party, crates.io)
    * features: default, std
  A stable_deref_trait 1.2.0 (transitive third-party, crates.io)
    * features: alloc, std
  M sha2 0.9.3 (direct third-party, crates.io)
    * version upgraded from 0.9.2
    * (unchanged features: default, std)
  M smallvec 1.6.1 (direct third-party, crates.io)
    * status changed from transitive third-party
    * (unchanged features: [none])
  M tokio-util 0.6.3 (direct third-party, crates.io)
    * version upgraded from 0.6.2
    * (unchanged features: codec, compat, default, futures-io, io)
  M libc 0.2.84 (transitive third-party, crates.io)
    * version upgraded from 0.2.82
    * (unchanged features: align, default, std)
  R async-stream 0.3.0 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  A rental-impl 0.5.5 (transitive third-party, crates.io)
    * features: [none]
  M syn 1.0.60 (direct third-party, crates.io)
    * added features: fold
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  M libc 0.2.84 (transitive third-party, crates.io)
    * version upgraded from 0.2.82
    * (unchanged features: default, std)
  R async-stream-impl 0.3.0 (transitive third-party, crates.io)
    * (old features: [none])
```
<!-- metadata: {"tag":"release-summary"} -->

2021-02-02 18:16 UTC, phlip9 commented
Ahh, the reason you're getting all these bot comments is that you included a merge commit in your change set. We explicitly ban merge commits, since we want a linear history (https://github.com/diem/diem/blob/master/CONTRIBUTING.md#responding-to-reviewer-feedback). To fix this, you're going to want to rebase and squash your changes into one commit on upstream/master. Make sure you also drop the merge commit as you're rebasing.

The next time you want to update your branch on top of master, try this instead of `git merge`

```sh
$ git fetch upstream
$ git rebase upstream/master
```

2021-02-03 07:06 UTC, davidiw approved these changes
thanks for the contribution, would probably have just made a single commit for this work in the future, but done is better than perfect :).
/land

2021-02-03 07:06 UTC, bors-libra commented
@davidiw :exclamation: This PR is still missing approvals, unable to queue for landing

2021-02-03 07:12 UTC, davidiw commented
/land

2021-02-03 08:12 UTC, closed without merging