[config] change default (0.0.0.0 -> localhost) for debug interface
diem/diem pull request #7445
Opened 2021-02-02 00:19 UTC by mimoo

This might be a breaking change for validators, depending on their configuration and how they are deployed.

2021-02-02 17:18 UTC, davidiw commented
Correct me if I'm wrong, but if we want to do this, we would need to update all of our deployment configurations, tutorials, and documentation. And also as far as I understand, no one is running this software on bare metal?

@mimoo perhaps the better approach is to document in the deployment process that if you do deploy this on bare metal, here are the risks.

cc: @mgorven

2021-02-02 17:27 UTC, mgorven requested changes
I believe this address is used for both the admission control debug port and the metrics port; changing the metrics port will break metrics collection in k8s deployment. I think we need to:

* Have separate values for the debug port and metrics port
* Default debug port to 127.0.0.1
* Default metrics port to 0.0.0.0

2021-02-04 22:33 UTC, mimoo commented
btw this PR is not here to drive this work, I just wanted to point out that we were exposing these publicly :) a volunteer needs to drive a change to secure default configurations :D

2021-02-05 06:46 UTC, davidiw commented
Then why submit this :P

2021-02-05 23:13 UTC, closed without merging