[safety-rules] error when no execution pubkey, but a vote proposal has a signature
diem/diem pull request #7679
Opened 2021-02-19 08:16 UTC by mimoo

I can't think of any malicious scenario that would trigger this, but this is probably a misconfiguration and we want to be alerted as soon as possible that something is going on.

Note that someone could use this to DoS the TCB by adding a signature to this request when the TCB is not configured to handle execution signatures. But there are many other ways to DoS the TCB (for example by sending an initialization request with a fake epoch change proof) so the assumption is that malicious consensus performing a DoS are out of scope.

2021-02-20 19:24 UTC, JoshLind reviewed
Thanks, @mimoo!

> I can't think of any malicious scenario that would trigger this,

I'm wondering about a (theoretical) scenario where signature verification has been disabled temporarily (e.g., to get around a key mismatch error for a temporarily amount of time). In this case, we'd probably want to ignore the signatures as opposed to error on the requests and prevent safety rules from making progress... But I'm also not sure this is a legitimate use-case. Perhaps @lightmark might know if there's an edge case we aren't considering here?

2021-02-20 19:24 UTC, JoshLind commented on consensus/safety-rules/src/error.rs
> +    #[error("execution signature present, but no public key to validate it")]
nits:
- Errors are ordered alphabetically in this list, can you move the error to the right location?
- Error strings should capitalize the first word (to be consistent). Could you also do that for "IncorrectRound".. not sure how it slipped through 😮

2021-02-21 22:17 UTC, davidiw requested changes
https://github.com/diem/diem/blob/master/consensus/safety-rules/src/safety_rules.rs#L54

It is an interesting change but it doesn't map to the mental model used when building this code, which was that the two pieces (LEC, LSR) need /not/ be configured synchronously in all cases. I could very well disabled verification of this data and not care how executor is configured. Imagine trying to debug the case, where you told safety rules not to validate but you're getting this new error.

See: https://github.com/diem/diem/blob/master/consensus/safety-rules/src/safety_rules.rs#L54

"Requested changes" isn't quite the right sentiment, this PR should not be landed.

2021-02-22 20:33 UTC, mimoo commented
makes sense : o

2021-02-22 20:33 UTC, closed without merging