[move-lang] do not coalesce nested loops into a shared header
diem/diem pull request #8039
Opened 2021-03-25 22:29 UTC by mengxu-fb

## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

2021-03-25 22:35 UTC, libra-action commented
**release binaries dependency change summary**:
```
target packages:
  A disassembler 0.1.0 (workspace, path 'language/tools/disassembler')
    * features: default
  A move-coverage 0.1.0 (workspace, path 'language/tools/move-coverage')
    * features: default
  A colored 2.0.0 (direct third-party, crates.io)
    * features: [none]
```
<!-- metadata: {"tag":"release-summary"} -->

2021-03-26 00:58 UTC, mengxu-fb commented on language/move-lang/src/shared/graph.rs
> +}
This file is copied from #7952 which originally exists as `move-prover/bytecode/src/graph.rs`

2021-03-26 16:18 UTC, tnowacki requested changes
Let's chat about this, if I understand the problem correctly, this can be done MUCH MUCH easier

2021-03-26 19:45 UTC, mengxu-fb commented
Closing in favor of #8049.

2021-03-26 19:45 UTC, closed without merging