[specifications] update section on signature checking in move adapter docs
diem/diem pull request #8478
Opened 2021-06-03 18:14 UTC by emmazzz

## Motivation

This PR updates the section on signature checking in Move adapter specification to include more details on verifying multi-agent txns.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes.

2021-06-10 16:43 UTC, bob-wilson requested changes
Besides the comments, it seems this is still missing something about the multi-agent prologue function.

2021-06-10 16:43 UTC, bob-wilson commented on specifications/move_adapter/README.md
> +pub enum RawTransactionWithData {
To be clear: I really like the addition of the `TransactionAuthenticator` enum here, so please keep that part for sure.

2021-06-20 22:17 UTC, emmazzz commented on specifications/move_adapter/README.md
> +pub enum RawTransactionWithData {
>  If `RawTransactionWithData` is not used directly in public APIs for the adapter, then it seems better not to mention it. I don't see anything else in this document that mentions it. Is that the case?
I see. That's right. `RawTransactionWithData` is not present in the public interfaces(`new`, `sign`, `verify`, etc). It is only a data structure that the signers should sign over. I will try to rephrase the text without mentioning `RawTransactionWithData`.

2021-06-21 18:43 UTC, bob-wilson commented on specifications/move_adapter/README.md
> +pub enum RawTransactionWithData {
This part looks good now. Thanks!

2021-06-21 18:43 UTC, bob-wilson commented
> Besides the comments, it seems this is still missing something about the multi-agent prologue function.

@emmazzz Did you see this comment?

2021-06-21 19:24 UTC, emmazzz commented
> > Besides the comments, it seems this is still missing something about the multi-agent prologue function.
> 
> @emmazzz Did you see this comment?

Ah I only looked at comments in the code and missed this one. Yes the description about multi-agent checks in the prologue in this doc is out-dated. I will add a bullet point in `Prologue Checks` mentioning the newly added prologue function.

2021-06-22 00:58 UTC, bob-wilson approved these changes
Looks good. Thanks!

2021-06-22 21:48 UTC, emmazzz commented
/land

2021-06-22 22:27 UTC, closed without merging