Bring back developers.diem.com folder and associated CI
diem/diem pull request #8762
Opened 2021-07-16 22:02 UTC by CapCap

This reverts commit 407d364aeb2918d2029c705081562bf183d89721.

## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

2021-07-19 16:19 UTC, rexhoffman requested changes

2021-07-19 16:19 UTC, rexhoffman commented on .github/workflows/developer-site-ci.yml
> +name: Diem Developers Website CI
this should likely live in ci-test.yml now, especially if the site not building on auto should prevent it landing on main.

2021-07-19 16:25 UTC, bmwill commented
Question on this: Would it be preferable to have the website live in its own repo again? I don't remember the reasoning why we moved it into the repo in the first place but it did have some consequences given we wanted to have both the rust documentation and the website hosted on the Github Pages site.

2021-07-19 17:25 UTC, davidiw commented
> Question on this: Would it be preferable to have the website live in its own repo again? I don't remember the reasoning why we moved it into the repo in the first place but it did have some consequences given we wanted to have both the rust documentation and the website hosted on the Github Pages site.

Would love to have a doc strategy -- having multiple different places for documentation means we have no strategy, no data, no waterfall, 🤯

2021-07-20 17:13 UTC, rexhoffman commented
My view is if it matters, put it in ci-test.yml.    Otherwise no one will see, or care about it.   Make sure to leverage the changes/matches action to only build when relevant changes occur.

2021-08-27 23:24 UTC, JoelMarcey commented
It was moved out because the developer.diem.com docs were moved to [Readme](https://readme.com/). Are we moving them back to being served from GitHub and/or Netlify? That would be the only reason why this PR would make sense. Also, the Move docs are part of this too and those are being handled separately.

I have not been in the meetings recently as I have been working on other things, but I would make sure this is what you want to do, maybe at the sync meeting on Monday?

2021-09-01 00:05 UTC, dahliamalkhi commented on developers.diem.com/docs/governance.mdx
> +
Should we avoid duplicating content here and just leave the reference to the TSC page?

2021-09-01 00:14 UTC, davidiw approved these changes
let's land this sucker
then do a thorough review of the content and design (sending updates where appropriate)
then do the rest of the migration

2021-09-01 00:14 UTC, davidiw commented
/land

2021-09-01 01:38 UTC, closed without merging