[diem-types] Change module publishing txn to take a bundle
diem/diem pull request #9655
Opened 2021-11-05 23:35 UTC by runtian-zhou

## Motivation

This will be a breaking change!

Change module publishing transaction from taking one single module to a list of modules the sender want to publish. This will significantly improve the usability of friend feature as friend modules can now be bundled together and publish in one transaction instead of having to separate them into three transactions.

Also breaking change is fine in this case because we never use module publishing transaction before in the system. 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Will add test in `e2e-testsuite`.

2021-11-08 23:34 UTC, xli commented
LGTM for the API changes.

2021-11-09 00:53 UTC, tzakian approved these changes
LGTM!

2021-11-09 19:49 UTC, runtian-zhou commented
Justification for the breaking change:
1. We never had such transaction in mainnet because module publishing transaction can only be sent by diem root with our current setup. And diem root never implemented such capability. This is why even though it's a breaking change it would be fine for the system.
2. We would be able to get rid of the old module publishing code that was never used by just changing the variant definition.

2021-11-09 20:33 UTC, runtian-zhou commented
cc @bmwill should I change the version number for `diem-types` here?

2021-11-09 23:31 UTC, runtian-zhou commented
Based on the discussion I don't think we need to update the version number here. That can go to the release of next sdk.

2021-11-10 05:00 UTC, xli requested changes

2021-11-10 05:00 UTC, xli commented on api/src/tests/transactions_test.rs
>              "type": "module_payload",
Same here should match new name

2021-11-10 19:53 UTC, bmwill commented
> cc @bmwill should I change the version number for `diem-types` here?

Nope, no need to do that now

2021-11-10 22:04 UTC, xli commented on api/doc/openapi.yaml
>      MoveModuleBytecodePayload:
for this `MoveModuleBytecodePayload`, you need remove `type` field. and add a type field to `ModuleBundlePayload` and set example: module_bundle_payload

2021-11-10 22:05 UTC, xli commented on api/doc/openapi.yaml
>      MoveModuleBytecodePayload:
also `MoveModuleBytecodePayload` is not a payload anymore, probably rename it to `MoveModuleBytecode`

2021-11-10 22:06 UTC, xli commented on api/doc/openapi.yaml
>      MoveModuleBytecodePayload:
actually, I found we have `MoveModuleBytecode`, so you should just remove `MoveModuleBytecodePayload` after replaced by `ModuleBundlePayload`

2021-11-11 00:17 UTC, xli commented on api/doc/openapi.yaml
> -          example: move_module_bytecode_payload
need type
example: module_bundle_payload

2021-11-11 00:18 UTC, xli commented on api/doc/openapi.yaml
> -        - bytecode
```
required:
  - type
  - modules
```

2021-11-11 01:38 UTC, runtian-zhou commented on api/doc/openapi.yaml
> -        - bytecode
Fixed!

2021-11-11 01:38 UTC, runtian-zhou commented on api/doc/openapi.yaml
> -          example: move_module_bytecode_payload
Fixed!

2021-11-11 16:52 UTC, xli submitted a review, later dismissed

2021-11-11 18:29 UTC, runtian-zhou commented
/land

2021-11-11 19:36 UTC, closed without merging