[cluster-test] Implement an parallel option for cluster test benchmark
diem/diem pull request #9735
Opened 2021-11-12 20:54 UTC by runtian-zhou

## Motivation

Implemente a cluster test option for enabling parallel execution in benchmark suite.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes
## Test Plan

TBD

2021-11-12 21:54 UTC, zekun000 reviewed
looks good to me, have you tried running the experiment?

2021-11-12 21:54 UTC, zekun000 commented on diem-node/src/lib.rs
> +        template.consensus.mempool_poll_count = u64::MAX;
not related?

2021-11-12 22:24 UTC, runtian-zhou commented on diem-node/src/lib.rs
> +        template.consensus.mempool_poll_count = u64::MAX;
Sry updated!

2021-11-12 23:07 UTC, zekun000 requested changes
the experiment doesn't work 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory '/diem/language/move-stdlib/sources'', language/move-stdlib/src/lib.rs:58:70
```

2021-11-12 23:14 UTC, runtian-zhou commented
> the experiment doesn't work
> 
> ```
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory '/diem/language/move-stdlib/sources'', language/move-stdlib/src/lib.rs:58:70
> ```

Hmm must be realted with how move modules are stored. Lemme check

2021-11-12 23:26 UTC, zekun000 commented
I think the problem is that source code is not available in the built image, there's only binaries

2021-11-16 23:33 UTC, bmwill commented
Could we instead add this to forge instead of cluster test since we're going to be turning down CT soon

2021-11-16 23:42 UTC, zihaoccc commented
> Could we instead add this to forge instead of cluster test since we're going to be turning down CT soon

I have synced with @runtian-zhou about this point, this pr actually is a one time run job to get some perf numbers for proving of concept purpose, since their last baseline is adjusted by CT, another experiment written in Forge is also out and will be added soon into Forge

2021-11-16 23:59 UTC, zekun000 commented
we'd need cluster test to demonstrate 5k tps since the machines forge uses only have 4 cores

2021-11-17 00:07 UTC, bmwill commented
Great if you're in the loop @zihaoccc then I'll get out of the way :)

2021-11-23 00:51 UTC, closed without merging

2021-11-23 00:52 UTC, runtian-zhou commented
Closing this PR as we will activate parallel execution benchmark in forge via a different genesis